[package]
name = "wasm"
version = "0.1.0"
authors = ["Frank Pobocek"]
edition = "2021"
path = "src/lib.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.82"

[dev-dependencies]
wasm-bindgen-test = "0.3.0"
